8 modelar dominio para gestionar partidos
leobz/organize-matches pull request #15
Opened 2022-08-31 22:34 UTC by juan-nisimura

Faltan algunas cosas, pero quería que tengan el código base para no atrasar con el resto:
 - Documentación del modelo de dominio.
 - Capaz unos tests, como crear un match sin parámetros.

2022-08-31 23:11 UTC, leobz commented on backend/src/main/java/matches/organizer/controller/MatchController.java
> +            throw new ResponseStatusException(HttpStatus.NOT_FOUND);
Si no hay partidos, no debe romper, se debe mostrar una lista vacia.

2022-09-01 00:22 UTC, FranCICSo commented on backend/src/main/java/matches/organizer/controller/MatchController.java
> +            throw new ResponseStatusException(HttpStatus.NOT_FOUND);
> Si no hay partidos, no debe romper, se debe mostrar una lista vacia.

Me está costando encontrar ejemplos de springboot en los que para responder un 404, no lo haga con una Exception y más aún que devuelvan un body. 
Creo que se puede lograr lo que decís @leobz pidiendo en el mensaje un `HttpServletResponse response` como parámetro a inyectar por spring, y meterle tanto el status como el body a la fuerza. Pero para mi con el response code alcanzaría. Si no, pregunten

2022-09-01 00:32 UTC, FranCICSo commented on backend/src/main/java/matches/organizer/service/MatchService.java
> +        catch (RuntimeException e) {
¿Porqué no lanzar la excepción para afuera si ocurre? En todo caso si tenemos miedo de devolver un 500 y queremos modelar los errores, se puede usar algo llamado [error handlers](https://www.baeldung.com/exception-handling-for-rest-with-spring)

2022-09-01 00:54 UTC, FranCICSo reviewed
Me estoy tratando de convencer el manejo de una única lista de players, con dos abstracciones de "startingPlayers" o "substitutePlayers". Me parece que va bien eso.
Temo que el hecho de tener un Dto , una clase de dominio y un builder, que si bien parece copado, pequemos un poco de sobrediseño  que nos mareemos y terminemos ignorando el Dto y usando la clase de dominio directamente. Pero lo dejo a discusión del equipo

2022-09-01 02:21 UTC, juan-nisimura commented
Ahí lo cambié usando ResponseStatusExceptionResolver. Se arroja la excepción y después spring la atrapa para devolver el response status. Lo probé medio a mano, pero también funciona con listas vacías.

2022-09-01 02:34 UTC, juan-nisimura commented
> 

Para aclarar un poco, yo también dudaba en usar el DTO, pero fue más necesidad que una decisión de diseño. Lo que ocurría es que el servidor devolvía siempre un estado de respuesta 500 cuando el objeto no era un POJO como el caso de la clase Match, que agrega métodos que no son getters. Para evitar el error, tuve que usar el DTO.

2022-09-01 23:53 UTC, FranCICSo commented
> > Me estoy tratando de convencer el manejo de una única lista de players, con dos abstracciones de "startingPlayers" o "substitutePlayers". Me parece que va bien eso. Temo que el hecho de tener un Dto , una clase de dominio y un builder, que si bien parece copado, pequemos un poco de sobrediseño que nos mareemos y terminemos ignorando el Dto y usando la clase de dominio directamente. Pero lo dejo a discusión del equipo
> 
> Para aclarar un poco, yo también dudaba en usar el DTO, pero fue más necesidad que una decisión de diseño. Lo que ocurría es que el servidor devolvía siempre un estado de respuesta 500 cuando el objeto no era un POJO como el caso de la clase Match, que agrega métodos que no son getters. Para evitar el error, tuve que usar el DTO.

Bien. Estaba revisando proyectos del laburo y hay algunos que en vez de DTO usan un objeto POJO llamado "Response", así que estaríamos en la misma. Si el Dto justamente lo usamos para transferir datos, debería estar bien. Otras clases de dominio tienen un `ObjectNode` y ese Json es el que se devuelve, pero por ahora no lo veo necesario

2022-09-01 23:57 UTC, FranCICSo requested changes
Me parece que hay unos temas con el `Player`

2022-09-01 23:57 UTC, FranCICSo commented on backend/src/main/java/matches/organizer/dto/PlayerDTO.java
> +    private UUID id;
¿Porqué el player tiene un id distinto al del usuario?
Creí que en la issue #8 decidimos que el Player era un usuario wrappeado para el match, sólo para tener la fecha de confirmación nomás, no que tenía entidad propia. 
**Player**

- User user (o sólo userId)
- LocalDateTime confirmationDate

**User**

- id
- alias
- fullName
- phone
- email
- password

2022-09-02 16:35 UTC, juan-nisimura commented on backend/src/main/java/matches/organizer/dto/PlayerDTO.java
> +    private UUID id;
Ya lo cambié, me había olvidado de cambiar los atributos de Player, de hecho también saqué el campo name que quedó de antes.
Aparte, hay uno de los tests que falla, estaba pensando que sería necesario un repositorio de players para resolverlo. Estuve tratando de hacer uno usando beans de spring pero no llegué a hacerlo funcionar. Si alguien que sepa más de esto lo puede resolver mejor. Sino, más tarde sigo investigando.

2022-09-02 17:38 UTC, FranCICSo commented on backend/src/main/java/matches/organizer/dto/PlayerDTO.java
> +    private UUID id;
Creo que no es un problema de spring el test que falla, pasa que en una lista de players se pregunta si contiene un usuario, y son cosas distintas. Ahí trato de arreglarlo

2022-09-02 18:29 UTC, FranCICSo commented on backend/src/main/java/matches/organizer/dto/PlayerDTO.java
> +    private UUID id;
Ahí hice un commit para resolver el caso del update de Match y que tenga sentido, y el formato de las fechas para que se vean como string y no como array

2022-09-02 18:31 UTC, FranCICSo commented on backend/src/main/java/matches/organizer/service/MatchService.java
> +        User anyUser = new User("Arthur", "Arthur Friedenreich", "Mi contraseña secreta");
El tema de la contraseña como texto plano en el objeto no va, pero todavía tenemos que ver bien cómo lo vamos a implementar

2022-09-02 18:31 UTC, FranCICSo approved these changes
Ya lo veo bien

2022-09-02 21:39 UTC, merged