1 crear partido
leobz/organize-matches pull request #28
Opened 2022-09-05 13:08 UTC by aleasquini

Cualquier sugerencia de mejora me dicen por favor.

2022-09-05 13:13 UTC, aleasquini commented
Hay que cambiar la respuesta del POST a algo como {"id": "4612356412315486131"}

2022-09-05 15:34 UTC, leobz commented on backend/src/main/java/matches/organizer/service/MatchService.java
> +    public String createMatchFromPost(String matchName, String matchLocation, LocalDate matchDate, LocalTime matchHour){
La capa deberia estar desacoplada de la logica del controller, por lo que el nombre del metodo no debe incluir el sufijo "Post". 
Podria ser simplemente "createMatch()" o similar

2022-09-05 15:38 UTC, leobz commented on backend/src/main/java/matches/organizer/service/MatchService.java
> +        Match anyMatch = new MatchBuilder()
Este nombre de variable se habia puesto porque se estaba hardcodeando un match para las primeras pruebas. Seria mas conveniente renombrarlo a "match"

2022-09-05 16:01 UTC, leobz commented on backend/src/main/java/matches/organizer/controller/MatchController.java
> +        return "Partido creado con ID: " + matchService.createMatchFromPost(oneMatch.getName(),oneMatch.getLocation(),oneMatch.getDate(),oneMatch.getHour());
La response esta especificada como JSON, pero se esta devolviendo un string.

Creeria que la respuesta mas indicada para el POST, es un JSON que contenga el objeto creado (Seria un return con el Objeto Java).

Las razones para devolver el objeto creado en el POST es una buena practica para obtener la nueva representacion del estado del objeto.
Adicionalmente, el status code deberia ser 201 (Created)

Dejo mas informacion sobre esto en los siguientes Links:
- https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#useful-post-responses
- https://stackoverflow.com/questions/19199872/best-practice-for-restful-post-response

2022-09-05 16:17 UTC, leobz commented on backend/src/test/java/matches/organizer/controller/MatchControllerTest.java
> +				"}")).andExpect(status().isOk());
Ademas de verificar que el status este bien, se deberia agregar un assert para verificar el contenido de la respuesta.
 Para eso se puede usar el metodo `content()`, aca hay un ejemplo de uso -> https://github.com/leobz/organize-matches/blob/main/backend/src/test/java/matches/organizer/controller/MatchControllerTest.java#L80

2022-09-05 16:24 UTC, leobz commented on backend/src/test/java/matches/organizer/controller/MatchControllerTest.java
> +				"}")).andExpect(status().isOk());
El test debe realizar la siguientes validaciones **para confirmar el caso de uso**:

- Antes de realizar el POST, la cantidad de matches debe ser igual a 0
- Despues de realizar el POST, la cantidad de matches debe ser igual a 1

Informacion de referencia:
- Antes de hacer el POST se deben limpiar los matches existentes del repositorio para que el Test no tenga datos basura de tests anteriores. Ver el siguiente metodo que esta en la rama `main `-> https://github.com/leobz/organize-matches/blob/main/backend/src/test/java/matches/organizer/controller/MatchControllerTest.java#L83
- Para contar la cantidad de matches, usar las funciones del repository (por ejemplo getAll(), obtener el listado y realizar un size() del listado. Con el numero obtenido verificar que sera 0 antes del POST y 1 despues del POST)

2022-09-06 01:29 UTC, FranCICSo commented on backend/src/main/java/matches/organizer/controller/MatchController.java
> +        return "Partido creado con ID: " + matchService.createMatchFromPost(oneMatch.getName(),oneMatch.getLocation(),oneMatch.getDate(),oneMatch.getHour());
¿y si `createMatchFromPost` recibe directamente el POSTMatchDTO no es mejor en vez de sacarle cada atributo para pasarlo como parámetro?

2022-09-06 01:32 UTC, FranCICSo requested changes

2022-09-06 01:32 UTC, FranCICSo commented on backend/src/main/java/matches/organizer/service/MatchService.java
> +                .setUserId(UUID.randomUUID())
tendrías que tomar el usuario desde el request. Si no estás recibiendo ninguno, deberías empezar a recibirlo. Creo que con recibir sólo el userId alcanza, pero no generar uno random acá porque no significa nada

2022-09-06 02:56 UTC, aleasquini commented on backend/src/main/java/matches/organizer/service/MatchService.java
> +                .setUserId(UUID.randomUUID())
Tal cual. Lo sumo al request

2022-09-06 16:09 UTC, FranCICSo approved these changes
a nivel de código lo veo bien

2022-09-06 17:41 UTC, merged