25 login logout
leobz/organize-matches pull request #60
Opened 2022-09-26 12:48 UTC by aleasquini

Cualquier cosa que vean para corregir, me avisan.
Mi test OK fue el siguiente: 
1) Crear user
2) Loguear user y guardar **token 2)** 
3) Pegarle al endpoint /users/private (lo deje comentado) con **token 2)** . OK
4) Logout con **token 2)** 
5) Pegarle al endpoint /user/private con **token 2)** . NO OK porque token está en blacklist

2022-09-26 21:27 UTC, leobz requested changes, later dismissed

2022-09-26 21:27 UTC, leobz commented on backend/src/main/java/matches/organizer/util/JwtUtils.java
> +        claims.put("name", user.getFullName());
Al ser las claims publicas (Esta encodeado en base 64 solamente), solo dejaria el dato del idUser, y quitaria las otras.
Tambien cambiaria `idUser` por `userId`.

2022-09-26 21:29 UTC, leobz commented on backend/src/main/java/matches/organizer/util/JwtUtils.java
> +        claims.put("idUser",user.getId().toString());
Al ser las claims publicas quitaría las opcionales, por temas de seguridad

2022-09-26 21:30 UTC, merged

2022-09-27 00:27 UTC, FranCICSo reviewed
Viendo que ya se mergeó, dejo pequeños comentarios para crear otra rama y corregir y que no nos lo marquen en la entrega

2022-09-27 00:27 UTC, FranCICSo commented on backend/src/main/java/matches/organizer/controller/AuthenticationController.java
> +        logger.info("THE USER WITH MAIL: " + userTryingLogin.getEmail() + " AND PASSWORD: " + userTryingLogin.getPassword() + " IS TRYING TO LOGIN");
no veo que se ofusque la password. No habría que loguear eso

2022-09-27 00:27 UTC, FranCICSo commented on backend/src/main/java/matches/organizer/controller/AuthenticationController.java
> +    public @ResponseBody Object logout(@RequestHeader(value = "authorization", defaultValue = "") String auth) throws Exception {
puede devolver String también, y no hace falta el @ResponseBody

2022-09-27 00:27 UTC, FranCICSo commented on backend/src/main/java/matches/organizer/controller/UserController.java
> +        //return userService.createUser(newUser).toJsonString();
¿porqué se sube código comentado?

2022-09-27 00:27 UTC, FranCICSo commented on backend/src/main/java/matches/organizer/service/AuthenticationService.java
> +    public JwtUtils getJwtUtils() {
Quitar esto porfa