68 be implementar load test
leobz/organize-matches pull request #72
Opened 2022-10-08 14:48 UTC by leobz

2022-10-08 23:57 UTC, FranCICSo reviewed
Sabes que me andan los tests de counter y matches, pero el de new-match me tira que no encuentra el vegeta en mi máquina ¿puede ser que no esté corriendo en el docker eso al final?
![image](https://user-images.githubusercontent.com/78270682/194731588-bb21c9b8-269b-4ff9-a6e2-8bfc51e67ae5.png)

2022-10-09 00:16 UTC, FranCICSo requested changes

2022-10-09 00:16 UTC, FranCICSo commented on Makefile
> +	else \
Con este código, si me corrió sin tener que tener vegeta instalado en la máquina; pero me tira un HTTP 400 el backend
```shell
else \
		docker run --network=host --rm -i peterevans/vegeta sh -c\
		"echo 'POST http://localhost:8081/matches\n@./body.json' > target.txt && \
		echo '{ \"name\": \"test\", \"location\": \"test\", \"dateAndTime\": \"2099-01-01T00:00:00.000Z\" }' > body.json && \
		vegeta attack -targets=target.txt \
		-header 'Cookie: token=$(token)' \
		-header 'Content-Type: application/json' \
		-format=http -duration=$(VEGETA_DURATION) -rate=$(VEGETA_RATE) -max-workers=$(VEGETA_MAX_WORKERS) \
		| tee results.bin | vegeta report \
		&& rm body.json && rm target.txt && rm results.bin ";\
	fi
```

2022-10-09 00:22 UTC, FranCICSo commented on Makefile
> +	else \
Me di cuenta que corría en mi máquina porque los archivos body.json y los txt quedaban en mi máquina en vez del contenedor

2022-10-09 03:56 UTC, leobz commented on Makefile
> +	else \
Gracias @FranCICSo ! Recien me fije, el problema es que `echo` no toma bien el ` \n` de esta linea `echo 'POST http://localhost:8081/matches\n@./body.json'`. Cambiandolo por `printf` funciona bien. Ahi lo arregle

2022-10-09 13:02 UTC, FranCICSo approved these changes
Listo, ya pude ejecutar los test de carga de creación de partidos (los tiré contra mi versión del mongo y en 10 segundos creó 13952 partidos).
![image](https://user-images.githubusercontent.com/78270682/194758220-efcea793-fa19-4dbb-b395-158036f615ea.png)
![image](https://user-images.githubusercontent.com/78270682/194758278-1b264103-930f-491c-a707-4446e6a25a9e.png)

2022-10-09 13:13 UTC, merged