57 Fix bug: Se pueden acceder a componentes privados sin estar autenticado
leobz/organize-matches pull request #81
Opened 2022-10-18 17:23 UTC by fernandofrontera

2022-10-18 17:56 UTC, leobz commented on frontend/src/routes/root.jsx
>                  console.log("Error on logout")
Al no estar la sesion iniciada, la llamada a `logout/` probablemente falle. Dejaria este `if` como está, pero el codigo que esta dentro del `else`, lo sacaría de dicho `else`, para que siempre se ejecute.

2022-10-29 21:20 UTC, FranCICSo requested changes

2022-10-29 21:20 UTC, FranCICSo commented on backend/src/main/java/matches/organizer/controller/AuthenticationController.java
> +        Cookie cookie = new Cookie("token", auth);
¿se podría tratar de meter en un método de `authenticationService` el código repetido? Más arriba veo estas 10 líneas de código sólo con la diferencia del maxage

2022-10-31 18:26 UTC, fernando-frontera commented on backend/src/main/java/matches/organizer/controller/AuthenticationController.java
> +        Cookie cookie = new Cookie("token", auth);
Done.

2022-10-31 18:26 UTC, fernando-frontera commented on frontend/src/routes/root.jsx
>                  console.log("Error on logout")
Se cambió el comportamiento del logout en el backend, donde ahora borra la cookie del token.

2022-11-01 04:44 UTC, merged